env:
  browser: true
  jquery: true
  es6: true
rules:
  getter-return:
    - warn
  no-cond-assign:
    - warn
  no-constant-condition:
    - warn
  no-dupe-args:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - warn
  no-empty-character-class:
    - warn
  indent:
    - warn
  no-undef:
    - warn