env:
  browser: true
  jquery: true
  es6: true
rules:
  indent:
    - error
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
    - "allowTemplateLiterals:true"
  semi:
    - warn
    - always
  # #Possible Errors
  # getter-return:
  #   - warn
  # no-cond-assign:
  #   - warn
  # no-constant-condition:
  #   - warn
  # no-dupe-args:
  #   - warn
  # no-dupe-keys:
  #   - warn
  # no-duplicate-case:
  #   - warn
  # no-empty:
  #   - warn
  # no-empty-character-class:
  #   - warn
  # no-ex-assign:
  #   - warn
  # no-extra-boolean-cast:
  #   - warn
  # no-extra-parens:
  #   - warn
  # no-func-assign:
  #   - warn
  # no-invalid-regexp:
  #   - warn
  # no-misleading-character-class:
  #   - warn
  # no-sparse-arrays:
  #   - warn
  # no-template-curly-in-string:
  #   - warn
  # no-unexpected-multiline:
  #   - warn
  # no-unreachable:
  #   - warn
  # no-unsafe-finally:
  #   - warn
  # no-unsafe-negation:
  #   - warn
  # use-isnan:
  #   - warn
  # valid-typeof:
  #   - warn
    
  # #Best Practices
  # accessor-pairs:
  #   - warn
  # block-scoped-var:
  #   - warn
  # curly:
  #   - warn
  # default-case:
  #   - warn
  # eqeqeq:
  #   - warn
  # no-lone-blocks:
  #   - warn
  # no-magic-numbers:
  #   - warn
  # no-multi-spaces:
  #   - warn
  # no-useless-catch:
  #   - warn
  # no-useless-return:
  #   - warn
  # yoda:
  #   - warn

  # #Variables
  # no-delete-var:
  #   - warn
  # no-undef:
  #   - warn
  # no-use-before-define:
  #   - warn
  # #Stylistic Issues
  # indent:
  #   - warn
  # no-mixed-spaces-and-tabs:
  #   - warn
  # no-unneeded-ternary:
  #   - warn
  # quotes:
  #   - warn
  
  # #ES6-Specific Rules
  # arrow-body-style:
  #   - warn
  # no-confusing-arrow:
  #   - warn
  # no-dupe-class-members:
  #   - warn
  # no-var:
  #   - warn
  # prefer-template:
  #   - warn
  